version: '3.2'

services:
  app:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../:/rails_app_test
      - test_node_modules_data:/rails_app_test/node_modules
      - test_tmp_data:/rails_app_test/tmp
    ports:
      - 3000:3000
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=rails_app_test"
      - "DATABASE_PASSWORD=password"
    networks:
      - rails_app_test_network
    depends_on:
      - db

  db:
    image: 'postgres:11.3'
    environment:
      - "POSTGRES_USER=rails_app_test"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - test_db-data:/var/lib/postgresql/data
    networks:
      - rails_app_test_network

volumes:
  test_node_modules_data:
  test_tmp_data:
  test_db-data:

networks:
  rails_app_test_network: