default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DATABASE_PORT") { '5432' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'rails_app_test' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  timeout: 5000

development:
  <<: *default
  database: rails_app_test_development

test:
  <<: *default
  database: rails_app_test_test

staging:
  <<: *default
  database: rails_app_test_staging

production:
  <<: *default
  database: rails_app_test_production
